/*
 * Copyright Collabora Ltd
 * SPDX-License-Identifier: MIT
 *
 * Autogenerated file, do not edit
 */

#include <stdint.h>

#include "libpan_shaders_v4.h"
const uint32_t *libpan_shaders_default_v4[LIBPAN_SHADERS_NUM_PROGRAMS] = {
};

