/*
 * Copyright Collabora Ltd
 * SPDX-License-Identifier: MIT
 *
 * Autogenerated file, do not edit
 */

#include <stdint.h>

#pragma once
#include "util/macros.h"

struct panlib_fill_args {
   uint64_t address;
   uint32_t value;
} PACKED;

static_assert(offsetof(struct panlib_fill_args, address) == 0, "");
static_assert(offsetof(struct panlib_fill_args, value) == 8, "");
static_assert(sizeof(struct panlib_fill_args) == 12, "");

struct panlib_fill_uint4_args {
   uint64_t address;
   uint32_t a;
   uint32_t b;
   uint32_t c;
   uint32_t d;
} PACKED;

static_assert(offsetof(struct panlib_fill_uint4_args, address) == 0, "");
static_assert(offsetof(struct panlib_fill_uint4_args, a) == 8, "");
static_assert(offsetof(struct panlib_fill_uint4_args, b) == 12, "");
static_assert(offsetof(struct panlib_fill_uint4_args, c) == 16, "");
static_assert(offsetof(struct panlib_fill_uint4_args, d) == 20, "");
static_assert(sizeof(struct panlib_fill_uint4_args) == 24, "");

struct panlib_fill_scalar_args {
   uint64_t address;
   uint32_t value;
} PACKED;

static_assert(offsetof(struct panlib_fill_scalar_args, address) == 0, "");
static_assert(offsetof(struct panlib_fill_scalar_args, value) == 8, "");
static_assert(sizeof(struct panlib_fill_scalar_args) == 12, "");

struct panlib_fill_uint4_scalar_args {
   uint64_t address;
   uint32_t a;
   uint32_t b;
   uint32_t c;
   uint32_t d;
} PACKED;

static_assert(offsetof(struct panlib_fill_uint4_scalar_args, address) == 0, "");
static_assert(offsetof(struct panlib_fill_uint4_scalar_args, a) == 8, "");
static_assert(offsetof(struct panlib_fill_uint4_scalar_args, b) == 12, "");
static_assert(offsetof(struct panlib_fill_uint4_scalar_args, c) == 16, "");
static_assert(offsetof(struct panlib_fill_uint4_scalar_args, d) == 20, "");
static_assert(sizeof(struct panlib_fill_uint4_scalar_args) == 24, "");

struct panlib_copy_query_result_args {
   uint64_t pool_addr;
   uint64_t available_addr;
   uint32_t query_stride;
   uint32_t first_query;
   uint32_t query_count;
   uint8_t _pad5[4];
   uint64_t dst_addr;
   uint64_t dst_stride;
   uint32_t query_type;
   uint32_t flags;
   uint32_t report_count;
} PACKED;

static_assert(offsetof(struct panlib_copy_query_result_args, pool_addr) == 0, "");
static_assert(offsetof(struct panlib_copy_query_result_args, available_addr) == 8, "");
static_assert(offsetof(struct panlib_copy_query_result_args, query_stride) == 16, "");
static_assert(offsetof(struct panlib_copy_query_result_args, first_query) == 20, "");
static_assert(offsetof(struct panlib_copy_query_result_args, query_count) == 24, "");
static_assert(offsetof(struct panlib_copy_query_result_args, dst_addr) == 32, "");
static_assert(offsetof(struct panlib_copy_query_result_args, dst_stride) == 40, "");
static_assert(offsetof(struct panlib_copy_query_result_args, query_type) == 48, "");
static_assert(offsetof(struct panlib_copy_query_result_args, flags) == 52, "");
static_assert(offsetof(struct panlib_copy_query_result_args, report_count) == 56, "");
static_assert(sizeof(struct panlib_copy_query_result_args) == 60, "");

struct panlib_clear_query_result_args {
   uint64_t pool_addr;
   uint64_t available_addr;
   uint32_t query_stride;
   uint32_t first_query;
   uint32_t query_count;
   uint32_t report_count;
   uint32_t availaible_value;
} PACKED;

static_assert(offsetof(struct panlib_clear_query_result_args, pool_addr) == 0, "");
static_assert(offsetof(struct panlib_clear_query_result_args, available_addr) == 8, "");
static_assert(offsetof(struct panlib_clear_query_result_args, query_stride) == 16, "");
static_assert(offsetof(struct panlib_clear_query_result_args, first_query) == 20, "");
static_assert(offsetof(struct panlib_clear_query_result_args, query_count) == 24, "");
static_assert(offsetof(struct panlib_clear_query_result_args, report_count) == 28, "");
static_assert(offsetof(struct panlib_clear_query_result_args, availaible_value) == 32, "");
static_assert(sizeof(struct panlib_clear_query_result_args) == 36, "");

struct panlib_indirect_dispatch_args {
   uint64_t cmd;
   uint32_t size_x;
   uint32_t size_y;
   uint32_t size_z;
   uint8_t _pad4[4];
   uint64_t indirect_job;
   uint64_t num_wg_sysval_x;
   uint64_t num_wg_sysval_y;
   uint64_t num_wg_sysval_z;
} PACKED;

static_assert(offsetof(struct panlib_indirect_dispatch_args, cmd) == 0, "");
static_assert(offsetof(struct panlib_indirect_dispatch_args, size_x) == 8, "");
static_assert(offsetof(struct panlib_indirect_dispatch_args, size_y) == 12, "");
static_assert(offsetof(struct panlib_indirect_dispatch_args, size_z) == 16, "");
static_assert(offsetof(struct panlib_indirect_dispatch_args, indirect_job) == 24, "");
static_assert(offsetof(struct panlib_indirect_dispatch_args, num_wg_sysval_x) == 32, "");
static_assert(offsetof(struct panlib_indirect_dispatch_args, num_wg_sysval_y) == 40, "");
static_assert(offsetof(struct panlib_indirect_dispatch_args, num_wg_sysval_z) == 48, "");
static_assert(sizeof(struct panlib_indirect_dispatch_args) == 56, "");

enum libpan_shaders_program {
    PANLIB_FILL = 0,
    PANLIB_FILL_UINT4 = 1,
    PANLIB_FILL_SCALAR = 2,
    PANLIB_FILL_UINT4_SCALAR = 3,
    PANLIB_COPY_QUERY_RESULT = 4,
    PANLIB_CLEAR_QUERY_RESULT = 5,
    PANLIB_INDIRECT_DISPATCH = 6,
    LIBPAN_SHADERS_NUM_PROGRAMS,
};


#define panlib_fill_struct(_context, _grid, _barrier, _data) do { \
   struct panlib_fill_args _args = _data;\
   MESA_DISPATCH_PRECOMP(_context, _grid, _barrier, PANLIB_FILL, &_args, sizeof(_args)); \
} while(0);

#define panlib_fill(_context, _grid, _barrier, address, value) do { \
   struct panlib_fill_args _args = {address, value};\
   MESA_DISPATCH_PRECOMP(_context, _grid, _barrier, PANLIB_FILL, &_args, sizeof(_args)); \
} while(0);

#define panlib_fill_uint4_struct(_context, _grid, _barrier, _data) do { \
   struct panlib_fill_uint4_args _args = _data;\
   MESA_DISPATCH_PRECOMP(_context, _grid, _barrier, PANLIB_FILL_UINT4, &_args, sizeof(_args)); \
} while(0);

#define panlib_fill_uint4(_context, _grid, _barrier, address, a, b, c, d) do { \
   struct panlib_fill_uint4_args _args = {address, a, b, c, d};\
   MESA_DISPATCH_PRECOMP(_context, _grid, _barrier, PANLIB_FILL_UINT4, &_args, sizeof(_args)); \
} while(0);

#define panlib_fill_scalar_struct(_context, _grid, _barrier, _data) do { \
   struct panlib_fill_scalar_args _args = _data;\
   MESA_DISPATCH_PRECOMP(_context, _grid, _barrier, PANLIB_FILL_SCALAR, &_args, sizeof(_args)); \
} while(0);

#define panlib_fill_scalar(_context, _grid, _barrier, address, value) do { \
   struct panlib_fill_scalar_args _args = {address, value};\
   MESA_DISPATCH_PRECOMP(_context, _grid, _barrier, PANLIB_FILL_SCALAR, &_args, sizeof(_args)); \
} while(0);

#define panlib_fill_uint4_scalar_struct(_context, _grid, _barrier, _data) do { \
   struct panlib_fill_uint4_scalar_args _args = _data;\
   MESA_DISPATCH_PRECOMP(_context, _grid, _barrier, PANLIB_FILL_UINT4_SCALAR, &_args, sizeof(_args)); \
} while(0);

#define panlib_fill_uint4_scalar(_context, _grid, _barrier, address, a, b, c, d) do { \
   struct panlib_fill_uint4_scalar_args _args = {address, a, b, c, d};\
   MESA_DISPATCH_PRECOMP(_context, _grid, _barrier, PANLIB_FILL_UINT4_SCALAR, &_args, sizeof(_args)); \
} while(0);

#define panlib_copy_query_result_struct(_context, _grid, _barrier, _data) do { \
   struct panlib_copy_query_result_args _args = _data;\
   MESA_DISPATCH_PRECOMP(_context, _grid, _barrier, PANLIB_COPY_QUERY_RESULT, &_args, sizeof(_args)); \
} while(0);

#define panlib_copy_query_result(_context, _grid, _barrier, pool_addr, available_addr, query_stride, first_query, query_count, dst_addr, dst_stride, query_type, flags, report_count) do { \
   struct panlib_copy_query_result_args _args = {pool_addr, available_addr, query_stride, first_query, query_count, {0}, dst_addr, dst_stride, query_type, flags, report_count};\
   MESA_DISPATCH_PRECOMP(_context, _grid, _barrier, PANLIB_COPY_QUERY_RESULT, &_args, sizeof(_args)); \
} while(0);

#define panlib_clear_query_result_struct(_context, _grid, _barrier, _data) do { \
   struct panlib_clear_query_result_args _args = _data;\
   MESA_DISPATCH_PRECOMP(_context, _grid, _barrier, PANLIB_CLEAR_QUERY_RESULT, &_args, sizeof(_args)); \
} while(0);

#define panlib_clear_query_result(_context, _grid, _barrier, pool_addr, available_addr, query_stride, first_query, query_count, report_count, availaible_value) do { \
   struct panlib_clear_query_result_args _args = {pool_addr, available_addr, query_stride, first_query, query_count, report_count, availaible_value};\
   MESA_DISPATCH_PRECOMP(_context, _grid, _barrier, PANLIB_CLEAR_QUERY_RESULT, &_args, sizeof(_args)); \
} while(0);

#define panlib_indirect_dispatch_struct(_context, _grid, _barrier, _data) do { \
   struct panlib_indirect_dispatch_args _args = _data;\
   MESA_DISPATCH_PRECOMP(_context, _grid, _barrier, PANLIB_INDIRECT_DISPATCH, &_args, sizeof(_args)); \
} while(0);

#define panlib_indirect_dispatch(_context, _grid, _barrier, cmd, size_x, size_y, size_z, indirect_job, num_wg_sysval_x, num_wg_sysval_y, num_wg_sysval_z) do { \
   struct panlib_indirect_dispatch_args _args = {cmd, size_x, size_y, size_z, {0}, indirect_job, num_wg_sysval_x, num_wg_sysval_y, num_wg_sysval_z};\
   MESA_DISPATCH_PRECOMP(_context, _grid, _barrier, PANLIB_INDIRECT_DISPATCH, &_args, sizeof(_args)); \
} while(0);


extern const uint32_t *libpan_shaders_default_v9[LIBPAN_SHADERS_NUM_PROGRAMS];
