/*
 * File generated with ../../../data1/01_Android17_EAP/external/mesa3d-rpi/src/gallium/auxiliary/driver_trace/enums2names.py, please do not edit manually.
 */
#include "tr_util.h"


const char *
tr_util_pipe_texture_target_name(enum pipe_texture_target value)
{
   switch (value) {
      case PIPE_BUFFER: return "PIPE_BUFFER";
      case PIPE_TEXTURE_1D: return "PIPE_TEXTURE_1D";
      case PIPE_TEXTURE_2D: return "PIPE_TEXTURE_2D";
      case PIPE_TEXTURE_3D: return "PIPE_TEXTURE_3D";
      case PIPE_TEXTURE_CUBE: return "PIPE_TEXTURE_CUBE";
      case PIPE_TEXTURE_RECT: return "PIPE_TEXTURE_RECT";
      case PIPE_TEXTURE_1D_ARRAY: return "PIPE_TEXTURE_1D_ARRAY";
      case PIPE_TEXTURE_2D_ARRAY: return "PIPE_TEXTURE_2D_ARRAY";
      case PIPE_TEXTURE_CUBE_ARRAY: return "PIPE_TEXTURE_CUBE_ARRAY";
      case PIPE_MAX_TEXTURE_TYPES: return "PIPE_MAX_TEXTURE_TYPES";

      default: return "PIPE_TEXTURE_TARGET_UNKNOWN";
   }
}


const char *
tr_util_pipe_shader_ir_name(enum pipe_shader_ir value)
{
   switch (value) {
      case PIPE_SHADER_IR_TGSI: return "PIPE_SHADER_IR_TGSI";
      case PIPE_SHADER_IR_NIR: return "PIPE_SHADER_IR_NIR";

      default: return "PIPE_SHADER_IR_UNKNOWN";
   }
}


const char *
tr_util_pipe_map_flags_name(enum pipe_map_flags value)
{
   switch (value) {
      case PIPE_MAP_NONE: return "PIPE_MAP_NONE";
      case PIPE_MAP_READ: return "PIPE_MAP_READ";
      case PIPE_MAP_WRITE: return "PIPE_MAP_WRITE";
      case PIPE_MAP_READ_WRITE: return "PIPE_MAP_READ_WRITE";
      case PIPE_MAP_DIRECTLY: return "PIPE_MAP_DIRECTLY";
      case PIPE_MAP_DISCARD_RANGE: return "PIPE_MAP_DISCARD_RANGE";
      case PIPE_MAP_DONTBLOCK: return "PIPE_MAP_DONTBLOCK";
      case PIPE_MAP_UNSYNCHRONIZED: return "PIPE_MAP_UNSYNCHRONIZED";
      case PIPE_MAP_FLUSH_EXPLICIT: return "PIPE_MAP_FLUSH_EXPLICIT";
      case PIPE_MAP_DISCARD_WHOLE_RESOURCE: return "PIPE_MAP_DISCARD_WHOLE_RESOURCE";
      case PIPE_MAP_PERSISTENT: return "PIPE_MAP_PERSISTENT";
      case PIPE_MAP_COHERENT: return "PIPE_MAP_COHERENT";
      case PIPE_MAP_THREAD_SAFE: return "PIPE_MAP_THREAD_SAFE";
      case PIPE_MAP_DEPTH_ONLY: return "PIPE_MAP_DEPTH_ONLY";
      case PIPE_MAP_STENCIL_ONLY: return "PIPE_MAP_STENCIL_ONLY";
      case PIPE_MAP_ONCE: return "PIPE_MAP_ONCE";
      case PIPE_MAP_DRV_PRV: return "PIPE_MAP_DRV_PRV";

      default: return "PIPE_MAP_FLAGS_UNKNOWN";
   }
}


const char *
tr_util_pipe_video_cap_name(enum pipe_video_cap value)
{
   switch (value) {
      case PIPE_VIDEO_CAP_SUPPORTED: return "PIPE_VIDEO_CAP_SUPPORTED";
      case PIPE_VIDEO_CAP_NPOT_TEXTURES: return "PIPE_VIDEO_CAP_NPOT_TEXTURES";
      case PIPE_VIDEO_CAP_MAX_WIDTH: return "PIPE_VIDEO_CAP_MAX_WIDTH";
      case PIPE_VIDEO_CAP_MAX_HEIGHT: return "PIPE_VIDEO_CAP_MAX_HEIGHT";
      case PIPE_VIDEO_CAP_PREFERRED_FORMAT: return "PIPE_VIDEO_CAP_PREFERRED_FORMAT";
      case PIPE_VIDEO_CAP_SUPPORTS_PROGRESSIVE: return "PIPE_VIDEO_CAP_SUPPORTS_PROGRESSIVE";
      case PIPE_VIDEO_CAP_MAX_LEVEL: return "PIPE_VIDEO_CAP_MAX_LEVEL";
      case PIPE_VIDEO_CAP_STACKED_FRAMES: return "PIPE_VIDEO_CAP_STACKED_FRAMES";
      case PIPE_VIDEO_CAP_MAX_MACROBLOCKS: return "PIPE_VIDEO_CAP_MAX_MACROBLOCKS";
      case PIPE_VIDEO_CAP_MAX_TEMPORAL_LAYERS: return "PIPE_VIDEO_CAP_MAX_TEMPORAL_LAYERS";
      case PIPE_VIDEO_CAP_SKIP_CLEAR_SURFACE: return "PIPE_VIDEO_CAP_SKIP_CLEAR_SURFACE";
      case PIPE_VIDEO_CAP_ENC_MAX_SLICES_PER_FRAME: return "PIPE_VIDEO_CAP_ENC_MAX_SLICES_PER_FRAME";
      case PIPE_VIDEO_CAP_ENC_SLICES_STRUCTURE: return "PIPE_VIDEO_CAP_ENC_SLICES_STRUCTURE";
      case PIPE_VIDEO_CAP_ENC_MAX_REFERENCES_PER_FRAME: return "PIPE_VIDEO_CAP_ENC_MAX_REFERENCES_PER_FRAME";
      case PIPE_VIDEO_CAP_VPP_ORIENTATION_MODES: return "PIPE_VIDEO_CAP_VPP_ORIENTATION_MODES";
      case PIPE_VIDEO_CAP_VPP_BLEND_MODES: return "PIPE_VIDEO_CAP_VPP_BLEND_MODES";
      case PIPE_VIDEO_CAP_VPP_MAX_INPUT_WIDTH: return "PIPE_VIDEO_CAP_VPP_MAX_INPUT_WIDTH";
      case PIPE_VIDEO_CAP_VPP_MAX_INPUT_HEIGHT: return "PIPE_VIDEO_CAP_VPP_MAX_INPUT_HEIGHT";
      case PIPE_VIDEO_CAP_VPP_MIN_INPUT_WIDTH: return "PIPE_VIDEO_CAP_VPP_MIN_INPUT_WIDTH";
      case PIPE_VIDEO_CAP_VPP_MIN_INPUT_HEIGHT: return "PIPE_VIDEO_CAP_VPP_MIN_INPUT_HEIGHT";
      case PIPE_VIDEO_CAP_VPP_MAX_OUTPUT_WIDTH: return "PIPE_VIDEO_CAP_VPP_MAX_OUTPUT_WIDTH";
      case PIPE_VIDEO_CAP_VPP_MAX_OUTPUT_HEIGHT: return "PIPE_VIDEO_CAP_VPP_MAX_OUTPUT_HEIGHT";
      case PIPE_VIDEO_CAP_VPP_MIN_OUTPUT_WIDTH: return "PIPE_VIDEO_CAP_VPP_MIN_OUTPUT_WIDTH";
      case PIPE_VIDEO_CAP_VPP_MIN_OUTPUT_HEIGHT: return "PIPE_VIDEO_CAP_VPP_MIN_OUTPUT_HEIGHT";
      case PIPE_VIDEO_CAP_ENC_QUALITY_LEVEL: return "PIPE_VIDEO_CAP_ENC_QUALITY_LEVEL";
      case PIPE_VIDEO_CAP_SUPPORTS_CONTIGUOUS_PLANES_MAP: return "PIPE_VIDEO_CAP_SUPPORTS_CONTIGUOUS_PLANES_MAP";
      case PIPE_VIDEO_CAP_ENC_SUPPORTS_MAX_FRAME_SIZE: return "PIPE_VIDEO_CAP_ENC_SUPPORTS_MAX_FRAME_SIZE";
      case PIPE_VIDEO_CAP_ENC_HEVC_BLOCK_SIZES: return "PIPE_VIDEO_CAP_ENC_HEVC_BLOCK_SIZES";
      case PIPE_VIDEO_CAP_ENC_HEVC_FEATURE_FLAGS: return "PIPE_VIDEO_CAP_ENC_HEVC_FEATURE_FLAGS";
      case PIPE_VIDEO_CAP_ENC_HEVC_PREDICTION_DIRECTION: return "PIPE_VIDEO_CAP_ENC_HEVC_PREDICTION_DIRECTION";
      case PIPE_VIDEO_CAP_REQUIRES_FLUSH_ON_END_FRAME: return "PIPE_VIDEO_CAP_REQUIRES_FLUSH_ON_END_FRAME";
      case PIPE_VIDEO_CAP_MIN_WIDTH: return "PIPE_VIDEO_CAP_MIN_WIDTH";
      case PIPE_VIDEO_CAP_MIN_HEIGHT: return "PIPE_VIDEO_CAP_MIN_HEIGHT";
      case PIPE_VIDEO_CAP_ENC_RATE_CONTROL_QVBR: return "PIPE_VIDEO_CAP_ENC_RATE_CONTROL_QVBR";
      case PIPE_VIDEO_CAP_ENC_AV1_FEATURE: return "PIPE_VIDEO_CAP_ENC_AV1_FEATURE";
      case PIPE_VIDEO_CAP_ENC_AV1_FEATURE_EXT1: return "PIPE_VIDEO_CAP_ENC_AV1_FEATURE_EXT1";
      case PIPE_VIDEO_CAP_ENC_AV1_FEATURE_EXT2: return "PIPE_VIDEO_CAP_ENC_AV1_FEATURE_EXT2";
      case PIPE_VIDEO_CAP_ENC_SUPPORTS_TILE: return "PIPE_VIDEO_CAP_ENC_SUPPORTS_TILE";
      case PIPE_VIDEO_CAP_ENC_MAX_TILE_ROWS: return "PIPE_VIDEO_CAP_ENC_MAX_TILE_ROWS";
      case PIPE_VIDEO_CAP_ENC_MAX_TILE_COLS: return "PIPE_VIDEO_CAP_ENC_MAX_TILE_COLS";
      case PIPE_VIDEO_CAP_ENC_INTRA_REFRESH: return "PIPE_VIDEO_CAP_ENC_INTRA_REFRESH";
      case PIPE_VIDEO_CAP_ENC_SUPPORTS_FEEDBACK_METADATA: return "PIPE_VIDEO_CAP_ENC_SUPPORTS_FEEDBACK_METADATA";
      case PIPE_VIDEO_CAP_ENC_H264_DISABLE_DBK_FILTER_MODES_SUPPORTED: return "PIPE_VIDEO_CAP_ENC_H264_DISABLE_DBK_FILTER_MODES_SUPPORTED";
      case PIPE_VIDEO_CAP_ENC_INTRA_REFRESH_MAX_DURATION: return "PIPE_VIDEO_CAP_ENC_INTRA_REFRESH_MAX_DURATION";
      case PIPE_VIDEO_CAP_ENC_H264_SUPPORTS_CABAC_ENCODE: return "PIPE_VIDEO_CAP_ENC_H264_SUPPORTS_CABAC_ENCODE";
      case PIPE_VIDEO_CAP_ROI_CROP_DEC: return "PIPE_VIDEO_CAP_ROI_CROP_DEC";
      case PIPE_VIDEO_CAP_ENC_ROI: return "PIPE_VIDEO_CAP_ENC_ROI";
      case PIPE_VIDEO_CAP_ENC_SURFACE_ALIGNMENT: return "PIPE_VIDEO_CAP_ENC_SURFACE_ALIGNMENT";
      case PIPE_VIDEO_CAP_ENC_HEVC_RANGE_EXTENSION_SUPPORT: return "PIPE_VIDEO_CAP_ENC_HEVC_RANGE_EXTENSION_SUPPORT";
      case PIPE_VIDEO_CAP_ENC_HEVC_RANGE_EXTENSION_FLAGS_SUPPORT: return "PIPE_VIDEO_CAP_ENC_HEVC_RANGE_EXTENSION_FLAGS_SUPPORT";
      case PIPE_VIDEO_CAP_ENC_MAX_LONG_TERM_REFERENCES_PER_FRAME: return "PIPE_VIDEO_CAP_ENC_MAX_LONG_TERM_REFERENCES_PER_FRAME";
      case PIPE_VIDEO_CAP_ENC_MAX_DPB_CAPACITY: return "PIPE_VIDEO_CAP_ENC_MAX_DPB_CAPACITY";
      case PIPE_VIDEO_CAP_ENC_DIRTY_RECTS: return "PIPE_VIDEO_CAP_ENC_DIRTY_RECTS";
      case PIPE_VIDEO_CAP_ENC_MOVE_RECTS: return "PIPE_VIDEO_CAP_ENC_MOVE_RECTS";
      case PIPE_VIDEO_CAP_ENC_GPU_STATS_QP_MAP: return "PIPE_VIDEO_CAP_ENC_GPU_STATS_QP_MAP";
      case PIPE_VIDEO_CAP_ENC_GPU_STATS_SATD_MAP: return "PIPE_VIDEO_CAP_ENC_GPU_STATS_SATD_MAP";
      case PIPE_VIDEO_CAP_ENC_GPU_STATS_RATE_CONTROL_BITS_MAP: return "PIPE_VIDEO_CAP_ENC_GPU_STATS_RATE_CONTROL_BITS_MAP";
      case PIPE_VIDEO_CAP_ENC_SLICED_NOTIFICATIONS: return "PIPE_VIDEO_CAP_ENC_SLICED_NOTIFICATIONS";
      case PIPE_VIDEO_CAP_ENC_DIRTY_MAPS: return "PIPE_VIDEO_CAP_ENC_DIRTY_MAPS";
      case PIPE_VIDEO_CAP_ENC_QP_MAPS: return "PIPE_VIDEO_CAP_ENC_QP_MAPS";
      case PIPE_VIDEO_CAP_ENC_MOTION_VECTOR_MAPS: return "PIPE_VIDEO_CAP_ENC_MOTION_VECTOR_MAPS";
      case PIPE_VIDEO_CAP_ENC_TWO_PASS: return "PIPE_VIDEO_CAP_ENC_TWO_PASS";
      case PIPE_VIDEO_CAP_ENC_GPU_STATS_PSNR: return "PIPE_VIDEO_CAP_ENC_GPU_STATS_PSNR";
      case PIPE_VIDEO_CAP_ENC_SPATIAL_ADAPTIVE_QUANTIZATION: return "PIPE_VIDEO_CAP_ENC_SPATIAL_ADAPTIVE_QUANTIZATION";
      case PIPE_VIDEO_CAP_ENC_READABLE_RECONSTRUCTED_PICTURE: return "PIPE_VIDEO_CAP_ENC_READABLE_RECONSTRUCTED_PICTURE";

      default: return "PIPE_VIDEO_CAP_UNKNOWN";
   }
}


const char *
tr_util_pipe_video_profile_name(enum pipe_video_profile value)
{
   switch (value) {
      case PIPE_VIDEO_PROFILE_UNKNOWN: return "PIPE_VIDEO_PROFILE_UNKNOWN";
      case PIPE_VIDEO_PROFILE_MPEG1: return "PIPE_VIDEO_PROFILE_MPEG1";
      case PIPE_VIDEO_PROFILE_MPEG2_SIMPLE: return "PIPE_VIDEO_PROFILE_MPEG2_SIMPLE";
      case PIPE_VIDEO_PROFILE_MPEG2_MAIN: return "PIPE_VIDEO_PROFILE_MPEG2_MAIN";
      case PIPE_VIDEO_PROFILE_VC1_SIMPLE: return "PIPE_VIDEO_PROFILE_VC1_SIMPLE";
      case PIPE_VIDEO_PROFILE_VC1_MAIN: return "PIPE_VIDEO_PROFILE_VC1_MAIN";
      case PIPE_VIDEO_PROFILE_VC1_ADVANCED: return "PIPE_VIDEO_PROFILE_VC1_ADVANCED";
      case PIPE_VIDEO_PROFILE_MPEG4_AVC_BASELINE: return "PIPE_VIDEO_PROFILE_MPEG4_AVC_BASELINE";
      case PIPE_VIDEO_PROFILE_MPEG4_AVC_CONSTRAINED_BASELINE: return "PIPE_VIDEO_PROFILE_MPEG4_AVC_CONSTRAINED_BASELINE";
      case PIPE_VIDEO_PROFILE_MPEG4_AVC_MAIN: return "PIPE_VIDEO_PROFILE_MPEG4_AVC_MAIN";
      case PIPE_VIDEO_PROFILE_MPEG4_AVC_EXTENDED: return "PIPE_VIDEO_PROFILE_MPEG4_AVC_EXTENDED";
      case PIPE_VIDEO_PROFILE_MPEG4_AVC_HIGH: return "PIPE_VIDEO_PROFILE_MPEG4_AVC_HIGH";
      case PIPE_VIDEO_PROFILE_MPEG4_AVC_HIGH10: return "PIPE_VIDEO_PROFILE_MPEG4_AVC_HIGH10";
      case PIPE_VIDEO_PROFILE_MPEG4_AVC_HIGH422: return "PIPE_VIDEO_PROFILE_MPEG4_AVC_HIGH422";
      case PIPE_VIDEO_PROFILE_MPEG4_AVC_HIGH444: return "PIPE_VIDEO_PROFILE_MPEG4_AVC_HIGH444";
      case PIPE_VIDEO_PROFILE_HEVC_MAIN: return "PIPE_VIDEO_PROFILE_HEVC_MAIN";
      case PIPE_VIDEO_PROFILE_HEVC_MAIN_10: return "PIPE_VIDEO_PROFILE_HEVC_MAIN_10";
      case PIPE_VIDEO_PROFILE_HEVC_MAIN_STILL: return "PIPE_VIDEO_PROFILE_HEVC_MAIN_STILL";
      case PIPE_VIDEO_PROFILE_HEVC_MAIN_12: return "PIPE_VIDEO_PROFILE_HEVC_MAIN_12";
      case PIPE_VIDEO_PROFILE_HEVC_MAIN10_444: return "PIPE_VIDEO_PROFILE_HEVC_MAIN10_444";
      case PIPE_VIDEO_PROFILE_HEVC_MAIN_422: return "PIPE_VIDEO_PROFILE_HEVC_MAIN_422";
      case PIPE_VIDEO_PROFILE_HEVC_MAIN10_422: return "PIPE_VIDEO_PROFILE_HEVC_MAIN10_422";
      case PIPE_VIDEO_PROFILE_HEVC_MAIN_444: return "PIPE_VIDEO_PROFILE_HEVC_MAIN_444";
      case PIPE_VIDEO_PROFILE_JPEG_BASELINE: return "PIPE_VIDEO_PROFILE_JPEG_BASELINE";
      case PIPE_VIDEO_PROFILE_VP9_PROFILE0: return "PIPE_VIDEO_PROFILE_VP9_PROFILE0";
      case PIPE_VIDEO_PROFILE_VP9_PROFILE2: return "PIPE_VIDEO_PROFILE_VP9_PROFILE2";
      case PIPE_VIDEO_PROFILE_AV1_MAIN: return "PIPE_VIDEO_PROFILE_AV1_MAIN";
      case PIPE_VIDEO_PROFILE_AV1_PROFILE2: return "PIPE_VIDEO_PROFILE_AV1_PROFILE2";
      case PIPE_VIDEO_PROFILE_MAX: return "PIPE_VIDEO_PROFILE_MAX";

      default: return "PIPE_VIDEO_PROFILE_UNKNOWN";
   }
}


const char *
tr_util_pipe_video_entrypoint_name(enum pipe_video_entrypoint value)
{
   switch (value) {
      case PIPE_VIDEO_ENTRYPOINT_UNKNOWN: return "PIPE_VIDEO_ENTRYPOINT_UNKNOWN";
      case PIPE_VIDEO_ENTRYPOINT_BITSTREAM: return "PIPE_VIDEO_ENTRYPOINT_BITSTREAM";
      case PIPE_VIDEO_ENTRYPOINT_IDCT: return "PIPE_VIDEO_ENTRYPOINT_IDCT";
      case PIPE_VIDEO_ENTRYPOINT_MC: return "PIPE_VIDEO_ENTRYPOINT_MC";
      case PIPE_VIDEO_ENTRYPOINT_ENCODE: return "PIPE_VIDEO_ENTRYPOINT_ENCODE";
      case PIPE_VIDEO_ENTRYPOINT_PROCESSING: return "PIPE_VIDEO_ENTRYPOINT_PROCESSING";

      default: return "PIPE_VIDEO_ENTRYPOINT_UNKNOWN";
   }
}


const char *
tr_util_pipe_video_vpp_orientation_name(enum pipe_video_vpp_orientation value)
{
   switch (value) {
      case PIPE_VIDEO_VPP_ORIENTATION_DEFAULT: return "PIPE_VIDEO_VPP_ORIENTATION_DEFAULT";
      case PIPE_VIDEO_VPP_ROTATION_90: return "PIPE_VIDEO_VPP_ROTATION_90";
      case PIPE_VIDEO_VPP_ROTATION_180: return "PIPE_VIDEO_VPP_ROTATION_180";
      case PIPE_VIDEO_VPP_ROTATION_270: return "PIPE_VIDEO_VPP_ROTATION_270";
      case PIPE_VIDEO_VPP_FLIP_HORIZONTAL: return "PIPE_VIDEO_VPP_FLIP_HORIZONTAL";
      case PIPE_VIDEO_VPP_FLIP_VERTICAL: return "PIPE_VIDEO_VPP_FLIP_VERTICAL";

      default: return "PIPE_VIDEO_VPP_ORIENTATION_UNKNOWN";
   }
}


const char *
tr_util_pipe_video_vpp_blend_mode_name(enum pipe_video_vpp_blend_mode value)
{
   switch (value) {
      case PIPE_VIDEO_VPP_BLEND_MODE_NONE: return "PIPE_VIDEO_VPP_BLEND_MODE_NONE";
      case PIPE_VIDEO_VPP_BLEND_MODE_GLOBAL_ALPHA: return "PIPE_VIDEO_VPP_BLEND_MODE_GLOBAL_ALPHA";

      default: return "PIPE_VIDEO_VPP_BLEND_MODE_UNKNOWN";
   }
}


const char *
tr_util_pipe_resource_param_name(enum pipe_resource_param value)
{
   switch (value) {
      case PIPE_RESOURCE_PARAM_NPLANES: return "PIPE_RESOURCE_PARAM_NPLANES";
      case PIPE_RESOURCE_PARAM_STRIDE: return "PIPE_RESOURCE_PARAM_STRIDE";
      case PIPE_RESOURCE_PARAM_OFFSET: return "PIPE_RESOURCE_PARAM_OFFSET";
      case PIPE_RESOURCE_PARAM_MODIFIER: return "PIPE_RESOURCE_PARAM_MODIFIER";
      case PIPE_RESOURCE_PARAM_HANDLE_TYPE_SHARED: return "PIPE_RESOURCE_PARAM_HANDLE_TYPE_SHARED";
      case PIPE_RESOURCE_PARAM_HANDLE_TYPE_KMS: return "PIPE_RESOURCE_PARAM_HANDLE_TYPE_KMS";
      case PIPE_RESOURCE_PARAM_HANDLE_TYPE_FD: return "PIPE_RESOURCE_PARAM_HANDLE_TYPE_FD";
      case PIPE_RESOURCE_PARAM_LAYER_STRIDE: return "PIPE_RESOURCE_PARAM_LAYER_STRIDE";
      case PIPE_RESOURCE_PARAM_DISJOINT_PLANES: return "PIPE_RESOURCE_PARAM_DISJOINT_PLANES";

      default: return "PIPE_RESOURCE_PARAM_UNKNOWN";
   }
}


const char *
tr_util_pipe_fd_type_name(enum pipe_fd_type value)
{
   switch (value) {
      case PIPE_FD_TYPE_NATIVE_SYNC: return "PIPE_FD_TYPE_NATIVE_SYNC";
      case PIPE_FD_TYPE_SYNCOBJ: return "PIPE_FD_TYPE_SYNCOBJ";
      case PIPE_FD_TYPE_TIMELINE_SEMAPHORE_D3D12: return "PIPE_FD_TYPE_TIMELINE_SEMAPHORE_D3D12";
      case PIPE_FD_TYPE_TIMELINE_SEMAPHORE_VK: return "PIPE_FD_TYPE_TIMELINE_SEMAPHORE_VK";

      default: return "PIPE_FD_TYPE_UNKNOWN";
   }
}


const char *
tr_util_pipe_blendfactor_name(enum pipe_blendfactor value)
{
   switch (value) {
      case PIPE_BLENDFACTOR_ONE: return "PIPE_BLENDFACTOR_ONE";
      case PIPE_BLENDFACTOR_SRC_COLOR: return "PIPE_BLENDFACTOR_SRC_COLOR";
      case PIPE_BLENDFACTOR_SRC_ALPHA: return "PIPE_BLENDFACTOR_SRC_ALPHA";
      case PIPE_BLENDFACTOR_DST_ALPHA: return "PIPE_BLENDFACTOR_DST_ALPHA";
      case PIPE_BLENDFACTOR_DST_COLOR: return "PIPE_BLENDFACTOR_DST_COLOR";
      case PIPE_BLENDFACTOR_SRC_ALPHA_SATURATE: return "PIPE_BLENDFACTOR_SRC_ALPHA_SATURATE";
      case PIPE_BLENDFACTOR_CONST_COLOR: return "PIPE_BLENDFACTOR_CONST_COLOR";
      case PIPE_BLENDFACTOR_CONST_ALPHA: return "PIPE_BLENDFACTOR_CONST_ALPHA";
      case PIPE_BLENDFACTOR_SRC1_COLOR: return "PIPE_BLENDFACTOR_SRC1_COLOR";
      case PIPE_BLENDFACTOR_SRC1_ALPHA: return "PIPE_BLENDFACTOR_SRC1_ALPHA";
      case PIPE_BLENDFACTOR_ZERO: return "PIPE_BLENDFACTOR_ZERO";
      case PIPE_BLENDFACTOR_INV_SRC_COLOR: return "PIPE_BLENDFACTOR_INV_SRC_COLOR";
      case PIPE_BLENDFACTOR_INV_SRC_ALPHA: return "PIPE_BLENDFACTOR_INV_SRC_ALPHA";
      case PIPE_BLENDFACTOR_INV_DST_ALPHA: return "PIPE_BLENDFACTOR_INV_DST_ALPHA";
      case PIPE_BLENDFACTOR_INV_DST_COLOR: return "PIPE_BLENDFACTOR_INV_DST_COLOR";
      case PIPE_BLENDFACTOR_INV_CONST_COLOR: return "PIPE_BLENDFACTOR_INV_CONST_COLOR";
      case PIPE_BLENDFACTOR_INV_CONST_ALPHA: return "PIPE_BLENDFACTOR_INV_CONST_ALPHA";
      case PIPE_BLENDFACTOR_INV_SRC1_COLOR: return "PIPE_BLENDFACTOR_INV_SRC1_COLOR";
      case PIPE_BLENDFACTOR_INV_SRC1_ALPHA: return "PIPE_BLENDFACTOR_INV_SRC1_ALPHA";

      default: return "PIPE_BLENDFACTOR_UNKNOWN";
   }
}


const char *
tr_util_pipe_blend_func_name(enum pipe_blend_func value)
{
   switch (value) {
      case PIPE_BLEND_ADD: return "PIPE_BLEND_ADD";
      case PIPE_BLEND_SUBTRACT: return "PIPE_BLEND_SUBTRACT";
      case PIPE_BLEND_REVERSE_SUBTRACT: return "PIPE_BLEND_REVERSE_SUBTRACT";
      case PIPE_BLEND_MIN: return "PIPE_BLEND_MIN";
      case PIPE_BLEND_MAX: return "PIPE_BLEND_MAX";

      default: return "PIPE_BLEND_FUNC_UNKNOWN";
   }
}


const char *
tr_util_pipe_logicop_name(enum pipe_logicop value)
{
   switch (value) {
      case PIPE_LOGICOP_CLEAR: return "PIPE_LOGICOP_CLEAR";
      case PIPE_LOGICOP_NOR: return "PIPE_LOGICOP_NOR";
      case PIPE_LOGICOP_AND_INVERTED: return "PIPE_LOGICOP_AND_INVERTED";
      case PIPE_LOGICOP_COPY_INVERTED: return "PIPE_LOGICOP_COPY_INVERTED";
      case PIPE_LOGICOP_AND_REVERSE: return "PIPE_LOGICOP_AND_REVERSE";
      case PIPE_LOGICOP_INVERT: return "PIPE_LOGICOP_INVERT";
      case PIPE_LOGICOP_XOR: return "PIPE_LOGICOP_XOR";
      case PIPE_LOGICOP_NAND: return "PIPE_LOGICOP_NAND";
      case PIPE_LOGICOP_AND: return "PIPE_LOGICOP_AND";
      case PIPE_LOGICOP_EQUIV: return "PIPE_LOGICOP_EQUIV";
      case PIPE_LOGICOP_NOOP: return "PIPE_LOGICOP_NOOP";
      case PIPE_LOGICOP_OR_INVERTED: return "PIPE_LOGICOP_OR_INVERTED";
      case PIPE_LOGICOP_COPY: return "PIPE_LOGICOP_COPY";
      case PIPE_LOGICOP_OR_REVERSE: return "PIPE_LOGICOP_OR_REVERSE";
      case PIPE_LOGICOP_OR: return "PIPE_LOGICOP_OR";
      case PIPE_LOGICOP_SET: return "PIPE_LOGICOP_SET";

      default: return "PIPE_LOGICOP_UNKNOWN";
   }
}

